In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("C:\\Users\\dell\\OneDrive\\Desktop\\xai-financial-sentiment\\data\\raw\\data.csv")

In [3]:
df = df.rename(columns={
    "Sentence": "text",
    "Sentiment": "label"
})

In [4]:
df.head()

                                                text     label
0  The GeoSolutions technology will leverage Bene...  positive
1  $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2  For the last quarter of 2010 , Componenta 's n...  positive
3  According to the Finnish-Russian Chamber of Co...   neutral
4  The Swedish buyout firm has sold its remaining...   neutral

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5842 entries, 0 to 5841
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    5842 non-null   object
 1   label   5842 non-null   object
dtypes: object(2)
memory usage: 91.4+ KB

In [6]:
print(df["label"].value_counts())

label
neutral     3130
positive    1852
negative     860
Name: count, dtype: int64

In [8]:
def clean_text(text):
    text = str(text)
    
    text = re.sub(r"\$\w+", "", text)  # remove stock tickers
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.lower().strip()

In [9]:
df["clean_text"] = df["text"].apply(clean_text)

In [10]:
df.head()

,text,label,clean_text
0,The GeoSolutions technology will leverage Bene...,positive,the geosolutions technology will leverage bene...
1,"$ESI on lows, down $1.50 to $2.50 BK a real po...",negative,on lows down to bk a real possibility
2,"For the last quarter of 2010 , Componenta 's n...",positive,for the last quarter of componenta s net sales...
3,According to the Finnish-Russian Chamber of Co...,neutral,according to the finnish russian chamber of co...
4,The Swedish buyout firm has sold its remaining...,neutral,the swedish buyout firm has sold its remaining...

In [11]:
label_map = {
    "positive": 1,
    "neutral": 0,
    "negative": -1
}

df["target"] = df["label"].map(label_map)

In [ ]:
# remove empty or very short text
df = df[df["clean_text"].str.len() > 20]

In [ ]:
# remove nulls
df = df.dropna()

In [ ]:
df.shape

In [ ]:
df["target"].value_counts().plot(kind="bar", title="Label Distribution")

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df.to_csv("C:\\Users\\dell\\OneDrive\\Desktop\\xai-financial-sentiment\\data\\processed\\cleaned_data.csv", index=False)